<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $currentTime = \Carbon\Carbon::now();
        $permissions = [
            [
               'uuid'=>\Illuminate\Support\Str::uuid()->toString(),
               'name'=> 'show_database_stats',
               'guard_name' => 'web',
               'module' => 'Dashboard Stats',
               'by_default' => true,
               'preference' => json_encode(\App\Models\Role::ALL_ROLES),
               'created_at' => $currentTime,
               'updated_at' => $currentTime,
            ],
            [
                'uuid'=>\Illuminate\Support\Str::uuid()->toString(),
                'name'=> 'can_search_flight',
                'guard_name' => 'web',
                'module' => 'Search Flights',
                'by_default' => true,
                'preference' => json_encode(\App\Models\Role::ALL_ROLES),
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
            ],
            [
                'uuid'=>\Illuminate\Support\Str::uuid()->toString(),
                'name'=> 'can_view_reservations',
                'guard_name' => 'web',
                'module' => 'Bookings',
                'by_default' => true,
                'preference' => json_encode(['head-office', 'branch', 'h-employee']),
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
            ],
            [
                'uuid'=>\Illuminate\Support\Str::uuid()->toString(),
                'name'=> 'can_view_void_requests',
                'guard_name' => 'web',
                'module' => 'Bookings',
                'by_default' => true,
                'preference' => json_encode(\App\Models\Role::MANAGMENT_ROLES),
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
            ],
            [
                'uuid'=>\Illuminate\Support\Str::uuid()->toString(),
                'name'=> 'can_view_my_void_requests',
                'guard_name' => 'web',
                'module' => 'Bookings',
                'by_default' => true,
                'preference' => json_encode(\App\Models\Role::AGENCY_ROLES),
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
            ],
            [
                'uuid'=>\Illuminate\Support\Str::uuid()->toString(),
                'name'=> 'can_view_branches',
                'guard_name' => 'web',
                'module' => 'Organizations',
                'by_default' => false,
                'preference' => json_encode(\App\Models\Role::HEAD_ROLES),
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
            ],
            [
                'uuid'=>\Illuminate\Support\Str::uuid()->toString(),
                'name'=> 'can_view_agencies',
                'guard_name' => 'web',
                'module' => 'Organizations',
                'by_default' => false,
                'preference' => json_encode(\App\Models\Role::MANAGMENT_ROLES),
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
            ],
            [
                'uuid'=>\Illuminate\Support\Str::uuid()->toString(),
                'name'=> 'can_view_employees',
                'guard_name' => 'web',
                'module' => 'Organizations',
                'by_default' => true,
                'preference' => json_encode(['head-office', 'branch', 'agency']),
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
            ],
            [
                'uuid'=>\Illuminate\Support\Str::uuid()->toString(),
                'name'=> 'can_view_bank_accounts_setting',
                'guard_name' => 'web',
                'module' => 'Settings',
                'by_default' => false,
                'preference' => json_encode(\App\Models\Role::HEAD_ROLES),
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
            ],
            [
                'uuid'=>\Illuminate\Support\Str::uuid()->toString(),
                'name'=> 'can_view_airline_margins_setting',
                'guard_name' => 'web',
                'module' => 'Settings',
                'by_default' => false,
                'preference' => json_encode(\App\Models\Role::HEAD_ROLES),
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
            ],
            [
                'uuid'=>\Illuminate\Support\Str::uuid()->toString(),
                'name'=> 'can_view_suppliers_setting',
                'guard_name' => 'web',
                'module' => 'Settings',
                'by_default' => false,
                'preference' => json_encode(\App\Models\Role::HEAD_ROLES),
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
            ],
            [
                'uuid'=>\Illuminate\Support\Str::uuid()->toString(),
                'name'=> 'can_view_connector_setting',
                'guard_name' => 'web',
                'module' => 'Settings',
                'by_default' => false,
                'preference' => json_encode(\App\Models\Role::HEAD_ROLES),
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
            ],
            [
                'uuid'=>\Illuminate\Support\Str::uuid()->toString(),
                'name'=> 'can_view_airlines_setting',
                'guard_name' => 'web',
                'module' => 'Settings',
                'by_default' => false,
                'preference' => json_encode(\App\Models\Role::HEAD_ROLES),
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
            ],
            [
                'uuid'=>\Illuminate\Support\Str::uuid()->toString(),
                'name'=> 'can_view_airports_setting',
                'guard_name' => 'web',
                'module' => 'Settings',
                'by_default' => false,
                'preference' => json_encode(\App\Models\Role::HEAD_ROLES),
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
            ],
            [
                'uuid'=>\Illuminate\Support\Str::uuid()->toString(),
                'name'=> 'can_view_countries_setting',
                'guard_name' => 'web',
                'module' => 'Settings',
                'by_default' => false,
                'preference' => json_encode(\App\Models\Role::HEAD_ROLES),
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
            ],
            [
                'uuid'=>\Illuminate\Support\Str::uuid()->toString(),
                'name'=> 'can_view_cities_setting',
                'guard_name' => 'web',
                'module' => 'Settings',
                'by_default' => false,
                'preference' => json_encode(\App\Models\Role::HEAD_ROLES),
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
            ],
            [
                'uuid'=>\Illuminate\Support\Str::uuid()->toString(),
                'name'=> 'can_view_news_setting',
                'guard_name' => 'web',
                'module' => 'Settings',
                'by_default' => false,
                'preference' => json_encode(\App\Models\Role::HEAD_ROLES),
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
            ],
            [
                'uuid'=>\Illuminate\Support\Str::uuid()->toString(),
                'name'=> 'can_view_agency_deposites',
                'guard_name' => 'web',
                'module' => 'Accounts',
                'by_default' => false,
                'preference' => json_encode(\App\Models\Role::MANAGMENT_ROLES),
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
            ],
            [
                'uuid'=>\Illuminate\Support\Str::uuid()->toString(),
                'name'=> 'can_view_branch_deposites',
                'guard_name' => 'web',
                'module' => 'Accounts',
                'by_default' => false,
                'preference' => json_encode(\App\Models\Role::HEAD_ROLES),
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
            ],
            [
                'uuid'=>\Illuminate\Support\Str::uuid()->toString(),
                'name'=> 'can_view_sales_report',
                'guard_name' => 'web',
                'module' => 'Reports',
                'by_default' => false,
                'preference' => json_encode(['head-office', 'h-employee', 'branch', 'b-employee', 'agency']),
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
            ],
            [
                'uuid'=>\Illuminate\Support\Str::uuid()->toString(),
                'name'=> 'can_view_transaction_history',
                'guard_name' => 'web',
                'module' => 'Reports',
                'by_default' => false,
                'preference' => json_encode(\App\Models\Role::ALL_ROLES),
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
            ],
            [
                'uuid'=>\Illuminate\Support\Str::uuid()->toString(),
                'name' => 'can_view_un_used_tickets',
                'guard_name' => 'web',
                'module' => 'Reports',
                'by_default' => true,
                'preference' => json_encode([\App\Models\Role::HEADOFFICE]),
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
            ],
            [
                'uuid'=>\Illuminate\Support\Str::uuid()->toString(),
                'name'=> 'can_view_notifications',
                'guard_name' => 'web',
                'module' => 'Notifications',
                'by_default' => true,
                'preference' => json_encode(\App\Models\Role::ALL_ROLES),
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
            ],
            [
                'uuid'=>\Illuminate\Support\Str::uuid()->toString(),
                'name'=> 'can_view_passenger_management',
                'guard_name' => 'web',
                'module' => 'Notifications',
                'by_default' => true,
                'preference' => json_encode(\App\Models\Role::ALL_ROLES),
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
            ],
            [
                'uuid'=>\Illuminate\Support\Str::uuid()->toString(),
                'name'=> 'can_view_my_bookings',
                'guard_name' => 'web',
                'module' => 'Bookings',
                'by_default' => true,
                'preference' => json_encode(['agency', 'sub-agent', 'a-employee']),
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
            ],
            [
                'uuid'=>\Illuminate\Support\Str::uuid()->toString(),
                'name'=> 'can_view_ag_pricing',
                'guard_name' => 'web',
                'module' => 'Finance',
                'by_default' => true,
                'preference' => json_encode(\App\Models\Role::AGENCY_ROLES),
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
            ],
            [
                'uuid'=>\Illuminate\Support\Str::uuid()->toString(),
                'name'=> 'can_view_payment_request',
                'guard_name' => 'web',
                'module' => 'Finance',
                'by_default' => false,
                'preference' => json_encode(\App\Models\Role::AGENCY_ROLES),
                'created_at' => $currentTime,
                'updated_at' => $currentTime,
            ],
        ];
        \Illuminate\Support\Facades\DB::table('permissions')->insert($permissions);
    }
}